### PR TITLE
Cross platform compatibility for windows and linux

### LINKED ISSUE #9: Question about cross platform compatibility pull request
Hi Melvin,
I noticed some people who are windows users (including me) have interest in your project as well so I have made the code compatible for both linux users and windows users. Would you like me to make a pull request?

### PR DESCRIPTION
**Pull request by Ben-0-mad**
changes:
- setup.py set_cfg_path function
- changed the name of download.py to download_format.py

The way I made it cross platform was by editing the setup.py so that it would generate the download.py file from download_format.py.
I wanted to avoid having to call an additional script just to generate download.py and that's why I generate it in the setup.py. At first I thought I could just use `os.path` and change a single line in the code to get the path working for windows as well but then I realised that when running the command 'tuedownloader {URL}' it will never recognise the right config path since tuedownloader runs from a different directory.

### CODE REVIEW

**Comment by MelvinKool** [comment]
Sorry for the late response, at the time I didn't really have a nice moment to work on it.
Looking at it now, I think that this PR introduces a few bugs.

- Setup.py has the console script tuedownloader.download:main, this was broken by commit 676ab79.
- We don't specify the permissions to open download_format.py.
- download_format.py was copied to a new file, instead of using `git mv`.
- The file path where the config file is located has been changed. This will break tuedownloader for current users (manual change needed).

Looking at your code, I see that we have to change the default config file directory (note that a workaround would be to use the --config option).
In Linux you have /etc/tuedownloader as the default config file directory, but in Windows config files are usually stored in a different location.
I think that we could solve this issue in a nicer way, e.g. by using the appdirs package or some other way to deal with config file locations in a cross-platform way.

If anyone knows a nice solution for this, please let me know.

**Comment by Ben-0-mad** [comment]
Thanks for taking the time to look at my code Melvin. That's very unfortunate to hear, sorry for having those bugs in my pull request.

**Comment by MelvinKool** [comment]
No problem, at the moment I'm fixing the script. Apparently they changed some pages. Having a good cross platform way for configuration files would be a good idea for sure.

**Comment by Ben-0-mad** [comment]
I agree with that!

**Pull request closed without merging**
